[build]
  publish = "dist"
  command = "yarn build"
  functions = "./functions"

[dev]
  dir = "dist"
  command = "yarn start"

[[redirects]]
  from = "/videos"
  to = "/.netlify/functions/videos"
  status = 200